
var particleData =
{
	initDone:false,
    banana:{"positionStyle":2,"positionBase":{"x":0,"y":0,"z":0},"positionRadius":3,"velocityStyle":2,"speedBase":20,"speedSpread":15,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"spark","particleTexture":"","sizeTween":{"times":[0.1,0.5,0.7],"values":[8,10,1]},"opacityTween":{"times":[0.2,0.7,1.5],"values":[0.75,1,0]},"colorTween":{"times":[0,0.2,1],"values":[{"x":0.18,"y":1,"z":0.3},{"x":0.18,"y":1,"z":0.9},{"x":0.18,"y":1,"z":1}]},"blendStyle":2,"particlesPerSecond":50,"particleDeathAge":0.2,"emitterDeathAge":0.2,"velocitySpread":{"x":0,"y":0,"z":0},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    saw_left:{"positionStyle":1,"positionBase":{"x":-30,"y":0,"z":0},"positionSpread":{"x":-20,"y":0,"z":10},"velocityStyle":1,"velocityBase":{"x":-50,"y":50,"z":0},"velocitySpread":{"x":-100,"y":100,"z":0},"accelerationBase":{"x":0,"y":-200,"z":0},"texture":"spikey","particleTexture":"","angleBase":0,"angleSpread":180,"angleVelocityBase":0,"angleVelocitySpread":1440,"sizeTween":{"times":[0,1],"values":[3,0.1]},"opacityTween":{"times":[1,2],"values":[1,0]},"colorTween":{"times":[0,0.5],"values":[{"x":0,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.5}]},"particlesPerSecond":100,"particleDeathAge":2,"emitterDeathAge":60,"accelerationSpread":{"x":0,"y":0,"z":0},"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    saw_right:{"positionStyle":1,"positionBase":{"x":20,"y":0,"z":0},"positionSpread":{"x":30,"y":0,"z":10},"velocityStyle":1,"velocityBase":{"x":50,"y":50,"z":0},"velocitySpread":{"x":100,"y":100,"z":0},"accelerationBase":{"x":0,"y":-200,"z":0},"texture":"spikey","particleTexture":"","angleBase":0,"angleSpread":180,"angleVelocityBase":0,"angleVelocitySpread":1440,"sizeTween":{"times":[0,1],"values":[3,0.1]},"opacityTween":{"times":[1,2],"values":[1,0]},"colorTween":{"times":[0,0.5],"values":[{"x":0,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.5}]},"particlesPerSecond":100,"particleDeathAge":2,"emitterDeathAge":60,"accelerationSpread":{"x":0,"y":0,"z":0},"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    stars:{"positionStyle":2,"positionBase":{"x":0,"y":0,"z":0},"positionRadius":5,"velocityStyle":2,"speedBase":50,"speedSpread":0.05,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"star","particleTexture":"","sizeTween":{"times":[0.1,0.5,0.7],"values":[1,10,1]},"opacityTween":{"times":[0.2,0.7,1.5],"values":[0.75,1,0]},"colorTween":{"times":[0,0.2,1],"values":[{"x":0.18,"y":1,"z":0.3},{"x":0.18,"y":1,"z":0.9},{"x":0.18,"y":1,"z":1}]},"blendStyle":2,"particlesPerSecond":50,"particleDeathAge":0.2,"emitterDeathAge":0.2,"velocitySpread":{"x":0,"y":0,"z":0},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0}
}

module.exports = particleData