
var particleData =
{
	initDone:false,
	banana_hit:{"positionStyle":2,"positionBase":{"x":0,"y":0,"z":0},"positionRadius":0,"velocityStyle":2,"speedBase":0,"speedSpread":0,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"glowFlare","particleTexture":"","sizeTween":{"times":[0,0.05,0.1],"values":[10,40,0]},"opacityTween":{"times":[0,0.5,0],"values":[1,1,1]},"colorTween":{"times":[0,0.1,0.2],"values":[{"x":0.15,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.9}]},"blendStyle":2,"particlesPerSecond":5,"particleDeathAge":0.2,"emitterDeathAge":0.2,"velocitySpread":{"x":0,"y":0,"z":0},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":10,"sizeSpread":0,"colorBase":{"x":0.18,"y":1,"z":0.5},"colorSpread":{"x":0.18,"y":1,"z":0.5},"opacityBase":1,"opacitySpread":0},
    banana_obtain:{"positionStyle":"1","positionBase":{"x":0,"y":0,"z":0},"positionRadius":3,"velocityStyle":"1","speedBase":20,"speedSpread":15,"accelerationBase":{"x":0,"y":-30,"z":1000},"texture":"spark","particleTexture":"","sizeTween":{"times":[0,0.1,0.4],"values":[20,10,5]},"opacityTween":{"times":[0.2,0.7,1.5],"values":[1,1,1]},"colorTween":{"times":[0,0.2,1],"values":[{"x":0.14,"y":1,"z":0.9},{"x":0.14,"y":1,"z":0.9},{"x":0.14,"y":1,"z":0.9}]},"blendStyle":1,"particlesPerSecond":15,"particleDeathAge":1,"emitterDeathAge":0.1,"velocitySpread":{"x":100,"y":100,"z":-150},"accelerationSpread":{"x":-50,"y":-100,"z":500},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":20,"sizeSpread":0,"colorBase":{"x":0.14,"y":1,"z":0.9},"colorSpread":{"x":0.14,"y":1,"z":0.9},"opacityBase":1,"opacitySpread":1,"positionSpread":{"x":5,"y":5,"z":0},"velocityBase":{"x":0,"y":0,"z":-150}},
    saw_left:{"positionStyle":1,"positionBase":{"x":-30,"y":0,"z":0},"positionSpread":{"x":-20,"y":0,"z":10},"velocityStyle":1,"velocityBase":{"x":-50,"y":50,"z":0},"velocitySpread":{"x":-100,"y":100,"z":0},"accelerationBase":{"x":0,"y":-200,"z":0},"texture":"spikey","particleTexture":"","angleBase":0,"angleSpread":180,"angleVelocityBase":0,"angleVelocitySpread":1440,"sizeTween":{"times":[0,1],"values":[5,0.1]},"opacityTween":{"times":[1,2],"values":[1,0]},"colorTween":{"times":[0,0.5],"values":[{"x":0,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.5}]},"particlesPerSecond":100,"particleDeathAge":2,"emitterDeathAge":60,"accelerationSpread":{"x":0,"y":0,"z":0},"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    saw_right:{"positionStyle":1,"positionBase":{"x":20,"y":0,"z":0},"positionSpread":{"x":30,"y":0,"z":10},"velocityStyle":1,"velocityBase":{"x":50,"y":50,"z":0},"velocitySpread":{"x":100,"y":100,"z":0},"accelerationBase":{"x":0,"y":-200,"z":0},"texture":"spikey","particleTexture":"","angleBase":0,"angleSpread":180,"angleVelocityBase":0,"angleVelocitySpread":1440,"sizeTween":{"times":[0,1],"values":[5,0.1]},"opacityTween":{"times":[1,2],"values":[1,0]},"colorTween":{"times":[0,0.5],"values":[{"x":0,"y":1,"z":0.5},{"x":0.16,"y":1,"z":0.5}]},"particlesPerSecond":100,"particleDeathAge":2,"emitterDeathAge":60,"accelerationSpread":{"x":0,"y":0,"z":0},"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    stars:{"positionStyle":2,"positionBase":{"x":0,"y":10,"z":0},"positionRadius":5,"velocityStyle":2,"speedBase":50,"speedSpread":0.05,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"star","particleTexture":"","sizeTween":{"times":[0.1,0.5,0.7],"values":[5,25,1]},"opacityTween":{"times":[0.2,0.7,1.5],"values":[0.75,1,0]},"colorTween":{"times":[0,0.2,1],"values":[{"x":0.18,"y":0.5,"z":1},{"x":0.18,"y":1,"z":0.9},{"x":0.18,"y":1,"z":1}]},"blendStyle":2,"particlesPerSecond":50,"particleDeathAge":0.2,"emitterDeathAge":0.2,"velocitySpread":{"x":0,"y":0,"z":0},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    hit_cloud:{"positionStyle":2,"positionBase":{"x":0,"y":10,"z":0},"positionRadius":3,"velocityStyle":2,"speedBase":10,"speedSpread":0.5,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"spark","particleTexture":"","sizeTween":{"times":[0.1,0.5,0.7],"values":[20,100,10]},"opacityTween":{"times":[0.2,0.2,0],"values":[0.75,1,0]},"colorTween":{"times":[0,0.1,0.2],"values":[{"x":0.15,"y":1,"z":0.6},{"x":0.16,"y":1,"z":0.8},{"x":0.16,"y":1,"z":0.3}]},"blendStyle":2,"particlesPerSecond":50,"particleDeathAge":0.2,"emitterDeathAge":0.2,"velocitySpread":{"x":0,"y":0,"z":0},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":0,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":0.5},"colorSpread":{"x":0,"y":0,"z":0},"opacityBase":1,"opacitySpread":0},
    banana_burst:{"positionStyle":"2","positionBase":{"x":0,"y":7,"z":0},"positionRadius":3,"velocityStyle":"1","speedBase":20,"speedSpread":15,"accelerationBase":{"x":0,"y":0,"z":0},"texture":"spark","particleTexture":"","sizeTween":{"times":[0,0.1,0.4],"values":[10,5,1]},"opacityTween":{"times":[0.2,0.7,1.5],"values":[1,1,1]},"colorTween":{"times":[0,0.2,1],"values":[{"x":0,"y":1,"z":1},{"x":0,"y":1,"z":1},{"x":0,"y":1,"z":1}]},"blendStyle":1,"particlesPerSecond":10,"particleDeathAge":0.7,"emitterDeathAge":0.3,"velocitySpread":{"x":100,"y":70,"z":100},"accelerationSpread":{"x":0,"y":0,"z":0},"angleBase":0,"angleSpread":0,"angleVelocityBase":0,"angleVelocitySpread":0,"angleAccelerationBase":0,"angleAccelerationSpread":0,"sizeBase":10,"sizeSpread":0,"colorBase":{"x":0,"y":1,"z":1},"colorSpread":{"x":0,"y":1,"z":1},"opacityBase":1,"opacitySpread":1,"positionSpread":{"x":2,"y":2,"z":0},"velocityBase":{"x":0,"y":0,"z":-50}}

}

module.exports = particleData